=== Уязвимость Zip Slip

Как разработчик, вы часто сталкиваетесь с zip-файлами. Например, подумайте о возможности загрузки или обработке набора CSV-файлов, которые загружаются как zip-файл. Команда Snyk Security обнаружила и ответственно раскрыла интересную уязвимость. Она использует обход пути, который можно использовать при извлечении файлов. С обходом пути вы пытаетесь перезаписать файлы за пределами предполагаемой целевой папки. Например, вы можете перезаписать команду `ls` при извлечении zip-файла. После того как эта команда будет заменена некоторыми дополнительными вредоносными действиями каждый раз, когда пользователь вводит `ls`, вы можете отправлять результат листинга на свой сервер, прежде чем показывать пользователю фактическую команду. Таким образом, вы получаете удаленное выполнение команды.

==== Проблема

Проблема возникает с тем, как мы извлекаем zip-файлы в Java; распространенный способ сделать это:

[source]
----
File destinationDir = new File("/tmp/zip");
Enumeration<? extends ZipEntry> entries = zip.entries();
while (entries.hasMoreElements()) {
  ZipEntry e = entries.nextElement();
  File f = new File(destinationDir, e.getName());
  InputStream is = zip.getInputStream(e);
  IOUtils.copy(is, write(f));
}
----

На первый взгляд, это выглядит нормально, и вы написали что-то в том же духе. Как мы видели в предыдущих заданиях, проблема в том, что вы можете использовать обход пути, чтобы выйти из `destinationDir` и начать идти к другим местам.

Но что, если мы получим zip-файл со следующим содержимым:

[source]
----
orders.csv
../../../../../../../tmp/evil.sh
----

Если вы распакуете zip-файл с кодом выше, файл будет сохранен в `/tmp/evil.sh`.
