=== Обход пути

Обход пути (каталога) — это уязвимость, при которой злоумышленник может получить доступ или сохранить файлы и каталоги вне
местоположения приложения. Это может привести к чтению файлов из других каталогов и перезаписи критических системных файлов в случае загрузки
файла.

=== Как это работает?

Например, предположим, что у нас есть приложение, которое размещает некоторые файлы в следующем
формате: `http://example.com/file=report.pdf` теперь как злоумышленник, вы, конечно, заинтересованы в других файлах, поэтому
вы пытаетесь `http://example.com/file=../../../../../etc/passwd.` В этом случае вы пытаетесь перейти в корень файловой системы,
а затем перейти в `/etc/passwd`, чтобы получить доступ к этому файлу. `../` называется dot-dot-slash, другое название
этой атаки.

Конечно, это простой пример, и в большинстве случаев он не будет работать, поскольку фреймворки реализуют элементы управления. Поэтому нам нужно проявить немного больше креативности и начать кодировать `../` до того, как запрос будет отправлен на сервер.
Например, если мы кодируем URL `../`, вы получите `%2e%2e%2f`, и веб-сервер, получающий этот запрос, снова декодирует его в `../`.

Также обратите внимание, что избегание приложений, фильтрующих эти кодировки, двойное кодирование также может сработать. Двойное кодирование
может быть необходимо, когда у вас есть система A, которая вызывает систему B. Система A будет декодировать только один раз и
вызовет B с все еще закодированным URL.
