=== Автоматическая поддержка фреймворков

Большинство фреймворков теперь поддерживают по умолчанию предотвращение CSRF. Например, в Angular перехватчик считывает токен
из cookie по умолчанию XSRF-TOKEN и устанавливает его в качестве заголовка HTTP, X-XSRF-TOKEN. Поскольку только код, работающий на вашем домене, может прочитать cookie, бэкенд может быть уверен, что HTTP-запрос поступил от вашего клиентского приложения, а не от злоумышленника.

Чтобы это работало, бэкенд-сервер устанавливает токен в cookie. Поскольку значение cookie должно считываться Angular (JavaScript), этот cookie не должен быть отмечен флагом http-only. При каждом запросе к серверу
Angular будет помещать токен в X-XSRF-TOKEN в качестве заголовка HTTP. Сервер может проверить, совпадают ли эти два токена, и это гарантирует, что запрос сервера выполняется в том же домене.

*Важно: ОПРЕДЕЛИТЕ ОТДЕЛЬНЫЙ ФАЙЛ COOKIE, НЕ ИСПОЛЬЗУЙТЕ СЕАНСНЫЙ COOKIE ПОВТОРНО*

Помните, что сеансовый cookie всегда должен быть определен с флагом http-only.

== Пользовательские заголовки небезопасны

Другой защитой может быть добавление пользовательского заголовка запроса к каждому вызову. Это сработает, если все взаимодействия
с сервером выполняются с помощью JavaScript. На стороне сервера вам нужно только проверить наличие этого заголовка
если этот заголовок отсутствует, отклоните запрос.
Некоторые фреймворки предлагают эту реализацию по умолчанию, однако исследователь Alex Infuhr обнаружил, что это также можно обойти. Вы можете прочитать о: https://insert-script.blogspot.com/2018/05/adobe-reader-pdf-client-side-request.html[Adobe Reader PDF - Client Side Request Injection]
