=== Что такое подделка межсайтовых запросов?

Подделка межсайтовых запросов, также известная как атака одним щелчком или сеансовая езда и сокращенно CSRF
(иногда произносится как sea-surf) или XSRF, — это тип вредоносного использования веб-сайта, при котором несанкционированные команды передаются
от пользователя, которому веб-сайт доверяет. В отличие от межсайтового скриптинга (XSS), который использует доверие пользователя к определенному сайту, CSRF
использует доверие, которое сайт имеет к браузеру пользователя.

Подделка межсайтовых запросов — это атака «запутавшегося заместителя» на веб-браузер. CSRF обычно имеет следующие характеристики:

* Он включает сайты, которые полагаются на личность пользователя.
* Он использует доверие сайта к этой личности.
* Он обманывает браузер пользователя, отправляя HTTP-запросы на целевой сайт.
* Он включает HTTP-запросы, которые имеют побочные эффекты.

Под угрозой находятся веб-приложения, которые выполняют действия на основе ввода данных от доверенных и аутентифицированных пользователей, не требуя от пользователя авторизации
определенного действия. Пользователь, аутентифицированный с помощью cookie-файла, сохраненного в веб-браузере пользователя, может неосознанно отправить HTTP-запрос на сайт,
который доверяет пользователю, и тем самым вызвать нежелательное действие.

Атака CSRF нацелена/злоупотребляет базовой функциональностью веб-сайта. Если сайт позволяет, это вызывает изменение состояния на сервере, например, изменение адреса электронной почты или пароля жертвы или покупку
чего-либо. Принуждение жертвы к извлечению данных не приносит пользы злоумышленнику, поскольку злоумышленник не получает ответ, а жертва получает.
Таким образом, атаки CSRF нацелены на запросы, изменяющие состояние.

Давайте продолжим с некоторыми упражнениями, чтобы рассмотреть способ выполнения запроса CSRF.
