= Настройки безопасности по умолчанию

Большой проблемой во всех типах систем является использование конфигураций по умолчанию.
Например, имя пользователя/пароли по умолчанию в маршрутизаторах, пароли по умолчанию для хранилищ ключей, режим без шифрования по умолчанию и т. д.

== Java cacerts

Установка пароля в файл cacerts имеет некоторые последствия. Это важно, когда необходимо защитить доверенные центры сертификации, а неизвестный самоподписанный центр сертификации не может быть добавлен слишком легко.

== Защита вашего закрытого ключа id_rsa

Вы используете ключ ssh для GitHub и/или других сайтов и оставляете его незашифрованным на своем диске? Или даже на своем облачном диске? По умолчанию генерация пары ключей ssh ​​оставляет закрытый ключ незашифрованным. Это упрощает его использование, и если он хранится в месте, куда можете зайти только вы, он обеспечивает достаточную защиту. Однако лучше зашифровать ключ. Когда вы захотите использовать ключ, вам придется снова указать пароль.

== Имя пользователя/пароль SSH для вашего сервера

Когда вы получаете виртуальный сервер от какого-либо хостинг-провайдера, обычно есть много не очень безопасных настроек по умолчанию. Одна из них заключается в том, что ssh для сервера работает на порту по умолчанию 22 и допускает попытки ввода имени пользователя/пароля. Одно из первых, что вам следует сделать, это изменить конфигурацию, чтобы вы не могли использовать ssh как пользователь root, и вы не могли использовать ssh, используя имя пользователя/пароль, но только с действительным и надежным ключом ssh. Если нет, то вы заметите постоянные попытки взломать ваш сервер методом подбора.

== Задание

В этом упражнении вам нужно извлечь секрет, который случайно был оставлен внутри образа контейнера docker. С помощью этого секрета вы можете расшифровать следующее сообщение: *U2FsdGVkX199jgh5oANElFdtCxIEvdEvciLi+v+5loE+VCuy6Ii0b+5byb5DXp32RPmT02Ek1pf55ctQN+DHbwCPiVRfFQamDmbHBUpD7as=*.
Вы можете расшифровать сообщение, войдя в работающий контейнер (docker exec ...) и получив доступ к файлу паролей, расположенному в /root. Затем используйте команду openssl внутри контейнера (для проблем с переносимостью в openssl на Windows/Mac/Linux)
Вы можете найти секрет в следующем образе docker, который вы можете запустить как:

	docker run -d webgoat/assignments:findthesecret

[source]
----
echo "U2FsdGVkX199jgh5oANElFdtCxIEvdEvciLi+v+5loE+VCuy6Ii0b+5byb5DXp32RPmT02Ek1pf55ctQN+DHbwCPiVRfFQamDmbHBUpD7as=" | openssl enc -aes-256-cbc -d -a -kfile ....
----
