= Основы криптографии

== Кодирование Base64

Кодирование — это не совсем криптография, но оно часто используется во всех видах стандартов, связанных с криптографическими функциями. Особенно кодирование Base64.

Кодирование Base64 — это метод, используемый для преобразования всех видов байтов в определенный диапазон байтов. Этот определенный диапазон — считываемые байты ASCII.
Таким образом, вы можете легче передавать двоичные данные, такие как секретные или закрытые ключи. Вы даже можете распечатать их или записать.
Кодирование также обратимо. Поэтому, если у вас есть закодированная версия, вы можете создать исходную версию.

В Википедии вы можете найти больше подробностей. По сути, он проходит по всем байтам и преобразует каждый набор из 6 бит в считываемый байт (8 бит).
В результате размер закодированных байтов увеличивается примерно на 33%.

	Hello ==> SGVsbG8=
	0x4d 0x61 ==> TWE=

=== Базовая аутентификация

Базовая аутентификация иногда используется веб-приложениями. Она использует кодировку base64.
Поэтому важно как минимум использовать Transport Layer Security (TLS или более известный как https), чтобы защитить других от чтения пароля имени пользователя, который отправляется на сервер.

	$echo -n "myuser:mypassword" | base64
	bXl1c2VyOm15cGFzc3dvcmQ=

HTTP-заголовок будет выглядеть так:

	Authorization: Basic bXl1c2VyOm15cGFzc3dvcmQ=
