= Основы криптографии

== Другое кодирование

Также используются другие кодирования.

=== Кодирование URL

Кодирование URL часто используется при отправке данных формы и параметров запроса на сервер. Поскольку пробелы в URL не допускаются, он затем заменяется на %20. Аналогичные замены производятся для других символов.

=== Кодирование HTML

Кодирование HTML гарантирует, что текст отображается в браузере как есть и не интерпретируется браузером как HTML.

=== UUEncode

Кодирование Unix-2-Unix использовалось для отправки вложений электронной почты.

=== Кодирование XOR

Иногда кодирование используется как первый и простой метод обфускации для хранения паролей.
Например, IBM WebSphere Application Server использует определенную реализацию кодирования XOR для хранения паролей в файлах конфигурации.
IBM рекомендует защищать доступ к этим файлам и заменять кодирование XOR по умолчанию на собственное пользовательское шифрование.
Однако, если эти рекомендации не соблюдаются, эти значения по умолчанию могут стать уязвимостью.

== Задание

Теперь давайте посмотрим, сможете ли вы узнать исходный пароль из этой закодированной XOR строки по умолчанию.
