= Шифрование

== Симметричное шифрование

Симметричное шифрование основано на общем секрете, который используется как для шифрования, так и для дешифрования. Поэтому обе стороны (участвующие в обмене секретами) используют один и тот же ключ.

Примеры протоколов:

* AES
* 3DES

== Асимметричное шифрование

Асимметричное шифрование основано на математических принципах, которые состоят из пары ключей. Два ключа обычно называются закрытым ключом и открытым ключом. Закрытый ключ должен быть очень хорошо защищен и известен только одной стороне. Все остальные могут свободно использовать открытый ключ. Что-то, зашифрованное закрытым ключом, может быть расшифровано всеми, у кого есть открытый ключ, а что-то, зашифрованное открытым ключом, может быть расшифровано только закрытым ключом.

Примеры протоколов:

* RSA
* DSA

== HTTPS использует как симметричные, так и асимметричные ключи

Вот краткое описание того, что происходит, если вы открываете браузер и переходите на сайт https.

* Ваш браузер подключается к серверу и получает сертификат веб-сервера
* Ваш браузер проверяет, доверяет ли он издателю сертификата, проверяя, находится ли сертификат издателя в его хранилище доверенных сертификатов. Это хранилище доверенных сертификатов управляется операционной системой и обновлениями браузера. А в некоторых корпоративных сетях им управляет компания. Из сертификата браузер получает открытый ключ.
* Теперь браузер генерирует случайные байты, которые будут использоваться для генерации симметричного ключа, и шифрует его открытым ключом сервера. Таким образом, только сервер может расшифровать его.
* В конце этого процесса и браузер, и веб-сервер будут использовать обмененный симметричный ключ (в процессе обмена асимметричными ключами) для шифрования и расшифровки сообщений, которые передаются туда и обратно между браузером и веб-сервером.

Симметричные ключи используются, поскольку их проще использовать с большими наборами данных, и при этом требуется меньше вычислительной мощности. Однако информация на этих страницах предназначена только для базового понимания криптографии. Более подробную информацию по этим темам можно найти в Интернете.
