= Основы криптографии

== Простое хеширование

Хеширование — это тип криптографии, который в основном используется для обнаружения изменения исходных данных. Из исходных данных генерируется хеш. Он основан на необратимых криптографических методах.
Если исходные данные изменены хотя бы на один байт, результирующий хеш также отличается.

Так что в некотором смысле это выглядит как безопасный метод. Однако это НЕ и даже НИКОГДА не является хорошим решением при использовании его для паролей. Проблема здесь в том, что вы можете генерировать пароли из словарей и вычислять всевозможные варианты этих паролей. Для каждого пароля вы можете вычислить хеш. Все это может храниться в больших базах данных. Поэтому всякий раз, когда вы находите хеш, который может быть паролем, вы просто ищете хеш в базе данных и узнаете пароль.

Некоторые алгоритмы хеширования больше не должны использоваться: MD5, SHA-1
Для этих хеш-кодов можно изменить полезную нагрузку таким образом, что она все равно будет давать тот же хеш. Это требует больших вычислительных мощностей, но все еще является возможным вариантом.

== Хеши с солью

Простые пароли, очевидно, не должны храниться в базе данных. И то же самое касается простых хешей.
В https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html[OWASP Password Storage Cheat Sheet,window=_blank] объясняется, что следует использовать, когда необходимо надежно сохранить информацию, связанную с паролями.

== Задание

Теперь давайте посмотрим, сможете ли вы найти, какие пароли соответствуют каким простым (unsalted) хэшам.
