= Хранилища ключей и хранилища доверия

Хранилище ключей — это место, где вы храните ключи. Помимо *_keystore_* часто используется также термин *_truststore_*. Хранилище доверия — это то же самое, что и хранилище ключей. Только оно обычно содержит только сертификаты (то есть, по сути, только открытые ключи и информацию об издателе) доверенных сертификатов или центров сертификации.

== Хранилища ключей на основе файлов

Хранилище ключей на основе файлов — это то, что в конечном итоге хранит ключи в файловой системе.

Хранение открытых сертификатов в хранилище ключей на основе файлов очень распространено

== Хранилища ключей в базах данных

Ключи и особенно открытые сертификаты, конечно, также могут храниться в базе данных.

== Аппаратное хранилище ключей

Аппаратное хранилище ключей — это система, которая имеет некое оборудование, содержащее фактические ключи.
Обычно это делается в средах с высоким уровнем безопасности, где закрытый ключ действительно является закрытым.
По сравнению с хранилищами ключей на основе файлов или баз данных невозможно сделать копию хранилища ключей, чтобы отправить ее в неизвестную и ненадежную среду.

Некоторые центры сертификации, которые используются для предоставления вам сертификата сервера для вашего веб-сайта, также создают для вас закрытые ключи (как услуга). Однако по определению это больше не считается закрытым ключом. Для всех типов хранилищ ключей вы должны хранить закрытый ключ в тайне и использовать запрос на подпись сертификата для заказа ваших сертификатов подписи или сервера.

== Управляемые хранилища ключей в операционной системе, браузере и других приложениях

Когда вы посещаете веб-сайт и ваш браузер сообщает, что сертификаты в порядке, это означает, что сертификат, используемый для веб-сайта, выдан доверенным центром сертификации. Но этот список доверенных центров сертификации управляется. Некоторые центры сертификации могут быть отозваны или удалены. Эти обновления происходят в фоновом режиме при установке обновлений браузера.
Не только браузер ведет список доверенных центров сертификации, операционная система также делает это. И среда выполнения Java также имеет свой собственный список, который хранится в файле cacerts. Обновления ОС и Java JRE поддерживают этот список в актуальном состоянии. В корпоративных средах они обычно поддерживаются компанией и также содержат корневые сертификаты компании.

== Дополнительная проверка сертификатов веб-сайтов с использованием записей DNS CAA

Некоторые компании проверяют весь или большую часть интернет-трафика. Даже те, где вы думаете, что у вас есть защищенное соединение end-2-end. Это работает следующим образом. Сотрудник открывает браузер и гуглит некоторую информацию. Браузер использует https и переходит на сайт Google. Ссылка выглядит реальной, и в браузере отображается замок. Однако, если вы проверите сертификат, вы можете заметить, что он был выдан одним из корневых центров сертификации вашей компании! Таким образом, вы установили защищенное соединение end-2-end с сервером вашей компании, и этот сервер имеет защищенное соединение с Google.
Чтобы предотвратить такие соединения man-in-middle с вашим сервером, современные браузеры теперь также проверяют записи DNS CAA, чтобы узнать, разрешен ли определенный издатель для определенного веб-сайта.
Дополнительная информация: https://en.wikipedia.org/wiki/DNS_Certification_Authority_Authorization[Wiki DNS CAA,window=_blank]

== Бесплатные сертификаты от Let's encrypt

https://letsencrypt.org[Let's encrypt,,window=_blank] бесплатный, автоматизированный и открытый центр сертификации. Он позволяет вам создавать действительные сертификаты для веб-сайтов, которые вы контролируете. Следуя и реализуя определенный протокол, ваша личность проверяется, и выдается сертификат. Сертификаты бесплатны, и это делается для того, чтобы стимулировать использование авторизованных сертификатов и снизить использование самоподписанных сертификатов в Интернете. Сертификаты действительны в течение 90 дней, поэтому их необходимо автоматически продлевать. (Что гарантирует, что подтверждение личности/права собственности также происходит часто)
