= Постквантовая

== Постквантовая криптография

Квантовые компьютеры уже здесь и с каждым годом получают все больше мощности в доступных кубитах. Квантовые компьютеры способны и будут способны расшифровывать информацию, которая была зашифрована с помощью алгоритмов, которые считались безопасными. Уже несколько лет регистрируется много зашифрованных сообщений с использованием квантовой уязвимой криптографии. Эта информация будет расшифрована, когда квантовые компьютеры станут достаточно мощными. Даже если информация может быть старой, она все еще может содержать ценную информацию, которую можно использовать не по назначению. Помимо того, что некоторая частная информация будет известна сторонам, для которых она не предназначалась.

Математика дает ответы для постквантовой эпохи. Новая криптография уже доступна и должна использоваться СЕЙЧАС, чтобы минимизировать угрозы. Вы можете прочитать больше об этом в Википедии: https://en.wikipedia.org/wiki/Post-quantum_cryptography[Post quatum on Wikipedia,window=_blank]

