= Подпись

Подпись — это хэш, который можно использовать для проверки действительности некоторых данных. Подпись может быть предоставлена отдельно от данных, которые она проверяет, или в случае CMS или SOAP может быть включена в тот же файл. (Когда части этого файла содержат данные, а части содержат подпись).

Подпись используется, когда важна целостность. Она предназначена для гарантии того, что данные, отправленные от Стороны-A Стороне-B, не были изменены. Поэтому Сторона-A подписывает данные, вычисляя хэш данных и шифруя этот хэш с помощью асимметричного закрытого ключа. Затем Сторона-B может проверить данные, вычисляя хэш данных и расшифровывая подпись, чтобы сравнить, являются ли оба хэша одинаковыми.

== RAW-подписи

Суть подписи RAW обычно вычисляется Стороной A следующим образом:

* создание хэша данных (например, хэша SHA-256)
* шифрование хэша с использованием асимметричного закрытого ключа (например, ключа RSA 2048 бит)
* (необязательно) кодирование двоичного зашифрованного хэша с использованием кодировки base64

Стороне B также необходимо получить сертификат с открытым ключом. Он мог быть передан ранее. Таким образом, задействовано как минимум 3 файла: данные, подпись и сертификат.

== Подписи CMS

Подпись CMS — это стандартизированный способ отправки данных + подписи + сертификата с открытым ключом в одном файле от Стороны A к Стороне B. Пока сертификат действителен и не отозван, Сторона B может использовать предоставленный открытый ключ для проверки подписи.

== Подписи SOAP

Подпись SOAP также содержит данные и подпись и, необязательно, сертификат. Все в одной полезной нагрузке XML. Существуют специальные шаги, связанные с вычислением хэша данных. Это связано с тем, что SOAP XML, отправляемый из системы в систему, может вводить дополнительные элементы или временные метки.
Кроме того, SOAP Signing дает возможность подписывать различные части сообщения разными сторонами.

== Подписи электронной почты

Отправка электронных писем не очень сложна. Вам нужно заполнить некоторые данные и отправить их на сервер, который их пересылает, и в конечном итоге они окажутся по назначению. Однако можно отправлять электронные письма с полем FROM, которое не является вашим собственным адресом электронной почты. Чтобы гарантировать получателю, что вы действительно отправили это электронное письмо, вы можете подписать свое электронное письмо. Доверенная третья сторона проверит вашу личность и выдаст сертификат подписи электронной почты. Вы устанавливаете закрытый ключ в своем почтовом приложении и настраиваете его для подписи отправляемых вами электронных писем. Сертификат выдается на определенный адрес электронной почты, и все другие, кто получит это электронное письмо, увидят указание на то, что отправитель проверен, поскольку их инструменты проверят подпись с использованием открытого сертификата, выданного доверенной третьей стороной.

== PDF или Word или другие подписи

Документы Adobe PDF и Microsoft Word также являются примерами вещей, которые поддерживают подпись. Подпись также находится внутри того же документа, что и данные, поэтому есть некоторое описание того, что является частью данных, а что — частью метаданных.
Правительства обычно отправляют официальные документы с PDF, содержащим сертификат.

== Задание

Вот простое задание. Вам отправляется закрытый ключ RSA. Определите модуль ключа RSA в виде шестнадцатеричной строки и вычислите подпись для этой шестнадцатеричной строки с помощью ключа. Упражнение требует некоторого опыта работы с OpenSSL. Вы можете поискать в Интернете полезные команды и/или использовать кнопку HINTS, чтобы получить некоторые советы.
