== Инструменты разработчика Google Chrome

Для выполнения определенных заданий вам иногда может потребоваться просмотреть исходный код JavaScript или выполнить команду JavaScript самостоятельно.
Для этого в Google Chrome есть набор инструментов, которые позволяют вам делать это и многое другое.
Хотя эти инструменты не являются специфическими для Google Chrome, почти в каждом современном браузере есть множество
своих. В нашем введении мы сосредоточимся на тех, которые есть в Google Chrome.
Однако вы все равно можете использовать браузер по своему выбору, например Firefox или Safari, хотя некоторые шаги этого руководства
могут отличаться для вас.

Помните, что следующее руководство не предназначено для того, чтобы научить вас всему об этих инструментах.
Это руководство будет сосредоточено только на основных знаниях для выполнения определенных заданий.
Кроме того, если вы уже знакомы с этими инструментами, вы можете спокойно пропустить эти уроки.

Чтобы начать: *откройте инструменты разработчика*. Есть несколько способов открыть их:

1. Щелкните правой кнопкой мыши в любом месте окна браузера и выберите опцию _«Проверить»_.
2. Перейдите в меню браузера (три точки в правом верхнем углу), затем перейдите в _«Дополнительные инструменты»_ и выберите опцию _«Инструменты разработчика»_.
3. Используйте сочетание клавиш _Ctrl + Shift + I_
