== Знание спецификации материалов OSS — это отправная точка

Современные приложения состоят из пользовательского кода и множества фрагментов с открытым исходным кодом. Разработчик обычно хорошо разбирается в своем пользовательском коде, но менее знаком с потенциальным риском используемых им библиотек/компонентов. Представьте спецификацию как список ингредиентов в рецепте.

=== Вопросы, на которые мы должны знать ответ:

* Как узнать, какие компоненты с открытым исходным кодом есть в наших приложениях?
** Как узнать, какие версии компонентов с открытым исходным кодом мы используем?
* Как определить риск компонентов с открытым исходным кодом?
* Как обнаружить риск компонентов с открытым исходным кодом?
** Как связать определенный риск с определенной версией компонента с открытым исходным кодом?
* Как узнать, когда компонент выпускает новую версию?
* Как узнать, обнаружена ли новая уязвимость в том, что ранее было «хорошим» компонентом?
* Как узнать, используем ли мы подлинную версию компонента с открытым исходным кодом?
