== Что такое сериализация

Сериализация — это процесс преобразования некоторого объекта в формат данных, который можно восстановить позже. Люди часто сериализуют объекты, чтобы сохранить их в хранилище или отправить в рамках коммуникаций. Десериализация — это обратный процесс, когда данные берутся из структурированного формата и перестраиваются в объект. Сегодня самым популярным форматом данных для сериализации данных является JSON. До этого это был XML.
----
a:4:{i:0;i:132;i:1;s:7:"Mallory";i:2;s:4:"user"; i:3;s:32:"b6a8b3bea87fe0e05022f8f3c88bc960";}
----

=== Собственная сериализация

Многие языки программирования предлагают собственную возможность сериализации объектов. Эти собственные форматы обычно предлагают больше возможностей, чем JSON или XML, включая настраиваемость процесса сериализации. К сожалению, возможности этих собственных механизмов десериализации могут быть повторно использованы для вредоносного эффекта при работе с ненадежными данными. Было обнаружено, что атаки на десериализаторы допускают атаки типа «отказ в обслуживании», «контроль доступа» и «удаленное выполнение кода».

=== Известные затронутые языки программирования
* PHP
* Python
* Ruby
* Java
* C
* C++

=== Данные, а не код

Сериализуются ТОЛЬКО данные. Сам код не сериализуется. Десериализация создает новый объект и копирует все данные из потока байтов, чтобы получить объект, идентичный объекту, который был сериализован.
