=== Стандарт паролей NIST

Стандарт паролей NIST (также известный как https://pages.nist.gov/800-63-3/sp800-63b.html[Специальные публикации (SP) 800-серий]) — это руководство, в котором содержатся рекомендации по внедрению безопасных систем паролей.

==== Правила паролей
Вот некоторые из наиболее важных рекомендаций, данных последним стандартом NIST:

- *нет правил составления* +
Не просите пользователя, например, использовать хотя бы одну заглавную букву и специальный символ в своем пароле.
Дайте им возможность сделать это, но не заставляйте!
- *нет подсказок к паролю* +
Если вы хотите, чтобы у людей было больше шансов угадать ваш пароль, запишите его на заметке, прикрепленной к экрану.
- *нет контрольных вопросов* +
Контрольные вопросы, также известные как аутентификация на основе знаний (KBA), устарели.
Спросить пользователя: «Как зовут вашего питомца?» или что-то подобное, чтобы проверить, не он ли это, довольно небезопасно.
- *никакой ненужной смены паролей*
Если вы хотите, чтобы пользователи подчинялись и выбирали длинные, трудно угадываемые пароли, вы не должны заставлять их менять эти пароли без необходимости после определенного периода.
- *минимальный размер 8 символов* +
Безопасный пароль в наши дни должен быть длиной НЕ МЕНЕЕ 8 символов (до 64).
Это минимум, а не максимум-минимум!
- *поддержка всех символов UNICODE* +
Было бы полезно, если бы вы разрешили использовать все виды символов UNICODE в пароле.
Это также включает эмодзи и пробелы.
- *проверьте пароль на наличие известных плохих вариантов*
* пароли, полученные из предыдущих корпусов взлома
* слова из словаря
* повторяющиеся или последовательные символы (например, 'aaaaaa', '1234abcd')
* контекстно-зависимые слова, такие как название службы, имя пользователя и их производные

==== Удобство использования

Помимо вышеперечисленных рекомендаций, стандарт NIST также рекомендует повысить удобство использования форм паролей, чтобы повысить вероятность выбора пользователями надежного и безопасного пароля. Вот некоторые из них:

- *разрешите вставку в поле ввода пароля* +
Пользователи должны иметь возможность использовать функцию «вставки» при вводе пароля.
Поскольку это облегчает использование менеджеров паролей, это также увеличивает вероятность того, что пользователь выберет надежный пароль.
- *разрешите отображение пароля* +
Ввод пароля должен иметь возможность отображать введенный пароль, чтобы помочь пользователю успешно ввести пароль.
- *предложить измеритель надежности* +
Добавьте измеритель надежности на страницу создания пароля, чтобы помочь пользователю выбрать надежный и безопасный пароль.
