=== Надежны ли ваши пароли?

А как насчет вас? Надежны ли ваши пароли?

Существуют специальные веб-сайты, которые позволяют выполнять поиск, если один из ваших аккаунтов был взломан в результате прошлой утечки данных. +
Перейдите на https://haveibeenpwned.com/Passwords[Have I Been Pwned] или https://www.dehashed.com/[DEHASHED] в качестве примера и проверьте, был ли взломан ваш аккаунт.
Если да, лучше сменить пароли *прямо сейчас*!

==== Что вы можете сделать, чтобы повысить безопасность своего аккаунта?
- *используйте разные пароли для разных аккаунтов* +
Лучше НЕ использовать один и тот же пароль для нескольких аккаунтов, а использовать разные пароли.
* *используйте парольные фразы* +
Используйте генераторы парольных фраз, такие как https://www.rempe.us/diceware/#eff[Diceware], для генерации парольных фраз.
Парольные фразы — это пароли, состоящие из нескольких слов, а не из случайно сгенерированных последовательностей символов.
Это делает их гораздо более простыми для запоминания для нас, людей. И кстати: чем длиннее, тем лучше!
* *используйте менеджер паролей* +
Если вы не можете запомнить разные пароли, используйте менеджер паролей для создания и безопасного хранения паролей.
- *используйте двухфакторную аутентификацию* +
Если возможно, используйте методы двухфакторной аутентификации, чтобы добавить дополнительный уровень безопасности к своим учетным записям.
