=== Хранение паролей

После создания надежного и безопасного пароля его также необходимо надежно хранить.
NIST дает рекомендации о том, как приложения должны обрабатывать пароли и как их надежно хранить.

==== Как следует хранить пароль?

- прежде всего: *используйте шифрование и защищенный канал для запроса паролей* +
Проверяющий должен использовать утвержденное шифрование и аутентифицированный защищенный канал для противодействия подслушиванию и атакам MitM (Man-in-the-middle) при запросе запомненных секретов.
- *устойчивый к офлайн-атакам* +
Пароли следует хранить в форме, устойчивой к офлайн-атакам.
- *используйте соли* +
Перед сохранением паролей их следует солить.
Соль должна иметь длину не менее 32 бит и должна выбираться произвольно, чтобы минимизировать коллизии значений соли среди сохраненных хэшей.
- *используйте хеширование* +
Перед сохранением пароля его следует хешировать с помощью односторонней функции деривации ключа.
Функция вводит пароль, соль и фактор стоимости, а затем генерирует хеш пароля. +
Примеры подходящих функций вывода ключей:
* Функция вывода ключа на основе пароля 2 (https://pages.nist.gov/800-63-3/sp800-63b.html#SP800-132[PBKDF2]) (как можно больше => не менее 10 000 итераций)
* https://pages.nist.gov/800-63-3/sp800-63b.html#SP800-132[BALLOON]
* Функция вывода ключа должна использовать утвержденную одностороннюю функцию, например:
** Код аутентификации сообщения с ключом (https://pages.nist.gov/800-63-3/sp800-63b.html#FIPS198-1[HMAC])
** любая утвержденная хеш-функция в https://pages.nist.gov/800-63-3/sp800-63b.html#SP800-107[SP 800-107]
** Безопасный алгоритм хэширования 3 (https://pages.nist.gov/800-63-3/sp800-63b.html#FIPS202[SHA-3])
** https://pages.nist.gov/800-63-3/sp800-63b.html#SP800-38B[CMAC]
** Код аутентификации сообщений Keccak (KMAC)
** Настраиваемый SHAKE (cSHAKE)
** https://pages.nist.gov/800-63-3/sp800-63b.html#SP800-185[ParallelHash]
- *функция вывода жесткого ключа памяти* +
Использовать Функции выведения ключей с жестким доступом к памяти для дальнейшего увеличения необходимых затрат на выполнение атак.
- *высокий фактор затрат* +
Фактор затрат функции выведения ключей (количество итераций) должен быть настолько большим, насколько позволяет производительность сервера проверки. (не менее 10 000 итераций)
