=== Подробнее о ведении журнала (2)

К настоящему моменту должно быть ясно, что использование простого кодирования/декодирования не является способом защиты конфиденциальной информации в журнале. Вместо этого лучше использовать другие методы: не вести журнал вообще, скрывать его или шифровать его с помощью другого общего секрета.

Есть еще несколько тем, которые мы, возможно, захотим здесь осветить:

- Как работать с уровнями журнала
- Как выполнять обработку исключений
- Как использовать ведение журнала для других целей
- Некоторые ресурсы для чтения.

==== Уровни журнала
Объяснение уровней журнала

==== Обработка исключений
обработка исключений (возможно, пример регистрации исключения для клиента с помощью криптографии и почему это плохая идея)

==== Ведение журнала аудита, мониторинг событий безопасности и журналы приложений
Обратите внимание, что ведение журнала часто используется не только для отладки приложений. Журналы приложений часто используются в качестве фида для других целей, подумайте о:

- *Аудит регистрации*: определенные события должны быть записаны вашим журналом приложений, чтобы создать след, который может быть использован для реконструкции действий, выполненных от имени/вашим пользователем. Это может быть позже использовано, например, в суде, чтобы доказать, что произошло в случае спора.
- *Мониторинг событий безопасности (SEM)*: события, сгенерированные вашим приложением, часто могут использоваться вашим отделом безопасности, чтобы понять, что происходит в ландшафте приложений организации. Существуют различные типы событий, а также различные атрибуты, которые могут играть роль в определении того, находится ли организация в беде. Например: привилегированный административный вход в систему, который используется только в качестве процедуры аварийного отключения, может уже быть очень ценным событием для них. Другой пример: хотя часто используемые административные входы в систему хорошо регистрировать, они могут не вызвать событие в отделе безопасности сами по себе, если только для этой административной роли не используется совершенно другое место. Упражнение по моделированию угроз с вашим отделом безопасности часто может помочь понять, какие типы журналов им требуются и что должно немедленно вызывать оповещение безопасности.
- *Обнаружение мошенничества*: ваши журналы приложений могут помочь в обнаружении мошенничества. Например: журналы, которые показывают, что кто-то пытается переместить больше денег, чем у него есть, могут указывать на то, что что-то идет не так.
- *Мониторинг бизнес-процессов*: ваши журналы приложений могут использоваться для проверки того, продолжают ли бизнес-процессы работать так, как им следует. Например: отсутствие новых событий на более низком уровне процесса может указывать на то, что бизнес-процесс остановлен. Это может быть ценной информацией для бизнеса, когда речь идет об управлении компанией.
- *И многое другое*...

Обратите внимание, что многие из этих целей журналирования довольно сильно отличаются друг от друга! Поэтому лучше всего отделить журналирование вашего приложения (отладки) от вашего SEM и журналов аудита с точки зрения вывода вашего приложения, хранения и обработки журналов в вашей организации.

==== Подробнее

- link:https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html[Памятка по ведению журнала OWASP]
