=== Подробнее о ведении журнала

Как вы уже поняли, подделка журнала может стать проблемой, когда пользователи пытаются подделать журналы. Есть разные способы сделать это, помимо отправки формы. Например, подумайте о параметрах URL или созданных полезных нагрузках JSON. Поэтому важно

- применить надлежащую очистку ввода
- убедиться, что вы можете установить подлинность источника и реализовать контроль целостности для обнаружения подделки журнала.
- убедиться, что пользователь не может вводить журналы из любого канала
- убедиться, что хранилище журнала защищено

Но безопасность журнала — это нечто большее, чем просто очистка от атак подмены. Давайте рассмотрим ведение журнала конфиденциальной информации.

==== Регистрация конфиденциальной информации

В предыдущем упражнении мы видели только проходящее имя пользователя, но не пароль. Почему? Потому что мы хотим убедиться, что журнал приложения не содержит никакой конфиденциальной информации. Давайте убедимся, что когда наши журналы будут скомпрометированы, нам не придется бояться повторного использования информации аутентификации.

Аналогично, мы не должны регистрировать никакую другую конфиденциальную информацию, такую как симметричные или закрытые ключи, токены доступа и т. д.

==== Регистрация личной информации

Будьте осторожны с регистрацией личной информации. Например: не регистрируйте данные банковского счета, личную идентифицируемую информацию, на регистрацию которой пользователь не давал согласия. Не регистрируйте факты, которые могут установить личность субъекта, регистрируемого в журнале.

В основном вы хотите предотвратить использование журналов людьми для профилирования людей или шпионажа за ними. Вы хотите защитить конфиденциальность субъектов, использующих вашу систему.

===== Особый случай: журналы доступа

Одним из особых случаев всегда являются журналы доступа, предлагаемые вашим сервером Ingress и/или приложений. Эти журналы должны содержать по крайней мере несколько вещей: откуда пришел запрос, когда был сделан запрос и, возможно, какой был код ответа. Дополнительная информация может быть передана в журнал доступа, в зависимости от безопасности журнала. Например: вы не хотите передавать необработанный запрос в журналы доступа, чтобы защитить конфиденциальность ваших пользователей.

И здесь часто начинается проблема: журналы доступа иногда фиксируют полный URL, используемый для запроса. Это может включать в себя конфиденциальные параметры URL. Поэтому: будьте осторожны с тем, что вы указываете в URL в качестве параметров, и убедитесь, что вы не регистрируете их в журнале с открытым доступом.

==== Читать далее

Хотите узнать больше о ведении журнала? Посмотрите:

- link:https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html[Памятка по ведению журнала OWASP]
- link:https://en.wikipedia.org/wiki/General_Data_Protection_Regulation#Principles[Статья GDPR в Википедии]
