= HTTP Basics

== Концепция

В этом уроке представлены основы понимания передачи данных между браузером и веб-приложением и того, как перехватывать запрос/ответ с помощью HTTP-прокси.

== Цели

Пользователь должен ознакомиться с функциями WebGoat, используя указанные выше кнопки для просмотра подсказок, отображения параметров HTTP-запроса, файлов cookie HTTP-запроса и исходного кода Java.
Вы можете использовать стандартные инструменты разработчика в своем браузере для просмотра HTTP-запроса и ответа.

=== Как работает HTTP:

Все HTTP-транзакции следуют одному и тому же общему формату. Каждый клиентский запрос и ответ сервера состоят из трех частей: строки запроса или ответа, раздела заголовка и тела сущности.

Клиент инициирует транзакцию следующим образом:

* Клиент связывается с сервером и отправляет запрос документа. Запрос GET может иметь параметры URL, и эти параметры будут доступны в журналах веб-доступа.

** GET /index.html?param=value HTTP/1.0

* Затем клиент отправляет необязательную информацию заголовка, чтобы сообщить серверу о своей конфигурации и форматах документов, которые он будет принимать.

** User-Agent: Mozilla/4.06 Accept: image/gif,image/jpeg, */*

* В запросе POST предоставленные пользователем данные будут следовать за необязательными заголовками и не являются частью URL-адреса POST.
