== Определите потенциал для DOM-Based XSS

DOM-Based XSS обычно можно найти, просматривая конфигурации маршрутов в клиентском коде.
Найдите маршрут, который принимает входные данные, «отражаемые» на странице.

Для этого примера вам нужно будет поискать какой-нибудь «тестовый» код в обработчиках маршрутов (WebGoat использует backbone в качестве своей основной библиотеки JavaScript).
Иногда тестовый код остается в производстве (и часто тестовый код прост и не имеет контроля безопасности или качества!).

Ваша цель — найти маршрут и использовать его. Но сначала, что такое базовый маршрут? В качестве примера посмотрите на URL этого урока ...
он должен выглядеть примерно так: /WebGoat/start.mvc#lesson/CrossSiteScripting.lesson/9. «Базовый маршрут» в этом случае:
*start.mvc#lesson/*
*CrossSiteScripting.lesson/9* после этого — это параметры, которые обрабатываются обработчиком маршрута JavaScript.

Итак, каков маршрут для тестового кода, который оставался в приложении во время производства?
Чтобы ответить на этот вопрос, вам нужно проверить исходный код JavaScript.
