== Что такое XSS?

Межсайтовый скриптинг (также известный как XSS) — это уязвимость/недостаток, который сочетает в себе разрешение HTML/тегов скриптов в качестве входных данных, которые отображаются в браузере без кодирования или очистки.

=== Межсайтовый скриптинг (XSS) — самая распространенная и пагубная проблема безопасности веб-приложений

Хотя есть простая и известная защита от этой атаки, в Интернете все еще много ее примеров. Охват исправлений также, как правило, является проблемой с точки зрения ее устранения. Мы поговорим подробнее о защите немного позже.

=== XSS оказывает значительное влияние

Особенно с учетом того, что «многофункциональные интернет-приложения» становятся все более распространенными, привилегированные вызовы функций, связанные с помощью JavaScript, могут быть скомпрометированы.
И если они не защищены должным образом, конфиденциальные данные (например, ваши файлы cookie аутентификации) могут быть украдены и использованы в чужих целях.

==== Короткие примеры:
* Из консоли JavaScript в инструментах разработчика браузера (Chrome, Firefox)
+
----
alert("XSS Test");
alert(document.cookie);
----
* Любое поле данных, возвращаемое клиенту, потенциально может быть внедрено
+
----
<script>alert("XSS Test")</script>
----

== Попробуйте! С помощью Chrome или Firefox

* Откройте вторую вкладку и используйте тот же URL, что и у этой страницы, на которой вы сейчас находитесь (или любой URL в этом экземпляре WebGoat).
* На второй вкладке откройте консоль JavaScript в инструментах разработчика и введите: `alert(document.cookie);`.
* Файлы cookie должны быть одинаковыми на каждой вкладке.
