== Защита от XSS

=== Почему?
Надеюсь, мы уже это рассмотрели. В конечном итоге, вы не хотите, чтобы чужой код работал в контексте ваших пользователей и их сеанса входа в систему

=== Что кодировать?
Основной предпосылкой защиты от XSS является *вывод кодировки* любого недоверенного ввода на экран.
Это может измениться с более сложными атаками, но это по-прежнему лучшая защита, которая у нас есть на данный момент. *И* ... *контекст имеет значение*

Еще одно слово о «недоверенном вводе». Если сомневаетесь, относитесь ко всему (даже к данным, которые вы заполнили в своей базе данных, как к недоверенным).
Иногда данные распределяются между несколькими системами, и то, что вы считаете своими данными, может быть создано не вами/вашей командой.

=== Когда/Где?
Кодировать *по мере отправки данных в браузер* (не в ваших сохраненных данных). В случае *Single Page Apps (SPA) вам нужно будет закодировать
в клиенте*. Подробности см. в вашей инфраструктуре/библиотеке, но некоторые ресурсы будут предоставлены на следующей странице.

=== Как?

* Кодировать как HTML Entities в HTML Body
* Кодировать как HTML Entities в HTML Attribute
* Кодировать для JavaScript, если вывод пользовательского ввода в JavaScript (но подумайте об этом... вы выводите пользовательский ввод в JavaScript на своей странице!!)

*НЕ* пытайтесь вносить в черный список/отрицательный фильтр для строк типа '<script>' и т. д.

...См. следующую страницу для некоторых рекомендуемых ресурсов и чтения по защите от XSS
