== Отраженный и основанный на DOM XSS

Основанный на DOM XSS — это еще одна форма отраженного XSS. Оба запускаются путем отправки ссылки с отраженными в браузере входными данными.
Разница между DOM и «традиционным» отраженным XSS заключается в том, что с DOM полезная нагрузка никогда не будет отправлена на сервер. Клиент будет только обрабатывать ее.

* Злоумышленник отправляет вредоносный URL жертве
* Жертва нажимает на ссылку
* Эта ссылка может загрузить вредоносную веб-страницу или веб-страницу, которую они используют (на которую вошли?), которая имеет уязвимый маршрут/обработчик
* Если это вредоносная веб-страница, она может использовать свой собственный JavaScript для атаки на другую страницу/URL с уязвимым маршрутом/обработчиком
* Уязвимая страница отображает полезную нагрузку и выполняет атаку в контексте пользователя на этой странице/сайте
* Вредоносный скрипт злоумышленника может запускать команды с привилегиями локальной учетной записи

* Жертва не осознает, что атака произошла* ... Злонамеренные злоумышленники не используют &lt;script&gt;alert('xss')&lt;/script&gt;
