== Что такое кодирование?

Недоверие пользовательскому вводу означает проверку данных на тип, длину, формат и диапазон всякий раз, когда они проходят через границу доверия,
например, из веб-формы в скрипт приложения, а затем кодирование их перед повторным отображением на динамической странице.

На практике это означает, что вам нужно просмотреть каждую точку на вашем сайте, где обрабатываются и обрабатываются предоставленные пользователем данные, и убедиться, что перед передачей обратно пользователю любые принятые со стороны клиента значения проверяются, фильтруются и кодируются.

На проверку на стороне клиента нельзя полагаться, но пользовательский ввод можно свести к минимальному алфавитно-цифровому набору с помощью обработки на стороне сервера, прежде чем он будет использован веб-приложением каким-либо образом.

== Экранирование

Экранирование означает, что вы преобразуете (или отмечаете) ключевые символы данных, чтобы предотвратить их интерпретацию в опасном контексте.

В случае вывода HTML вам необходимо преобразовать символы < и > (среди прочих), чтобы предотвратить отображение любого вредоносного кода.
Экранирование этих символов подразумевает их преобразование в эквиваленты сущностей \&lt; и \&gt;,
которые не будут интерпретироваться браузером как теги HTML.

== Специальные символы

Вам необходимо закодировать специальные символы, такие как "<" и ">", прежде чем они будут повторно отображены, если они получены из пользовательского ввода.
Например, кодирование "<" и ">" гарантирует, что браузер отобразит <script>, но не выполнит его.
В сочетании с кодированием ваши веб-страницы всегда должны определять свой набор символов, чтобы браузер не интерпретировал
специальные кодировки символов из других наборов символов.

Атаки с использованием межсайтового скриптинга обычно происходят, когда вам удается внедрить скрипт (обычно javascript) на чужой веб-сайт, где он может быть запущен вредоносно.

=== Соответствующие специальные символы XML/HTML

|===
|Char |Escape string |
|< |\&lt;|
|> |\&gt;|
|" |\&quot;|
|' |\&#x27;|
|& |\&amp;|
|/  |\&#x2F;|

|===
