== Безопасные ссылки на объекты

=== Начните с конечной цели
Задокументирован ли у вас контроль доступа? Если нет, как вы можете его обеспечить? Контроль доступа определяется
бизнес-логикой, которая управляет приложением и/или конфиденциальностью и другими законами.

==== Горизонтальный и вертикальный контроль доступа
Часто мы думаем о контроле доступа в терминах «ролей» (пользователь, опытный пользователь, администратор и т. д.).
Однако, как отмечалось в предыдущих упражнениях, пользователи с одинаковой «ролью» могут получать доступ к данным друг друга. Это
горизонтальный контроль доступа. Оба должны быть обеспечены.

.Пример матрицы контроля доступа
|===
|Endpoint | Method | Description | Roles, Access Rules | Notes, Caveats

| /profile
| GET
| просмотр профиля пользователя
| Авторизованный пользователь, может просматривать только свою собственную роль
| Роли администратора должны использовать diff Url для просмотра профилей других (см. ниже)

| /profile/{id}
| GET
| просмотр профиля пользователя для указанного пользователя
| Авторизованный пользователь может просматривать свой профиль по {id}, администраторы также могут просматривать
| n/a

| /profile/{id}
| PUT
| изменить профиль пользователя. объект профиля отправлен клиентом с запросом
| Авторизован Пользователь может редактировать свой профиль по {id}, администраторы также могут редактировать.
| Редактирование администратора должно быть авторизовано
|===

==== Аудит доступа
Как показано в примере выше, ваши правила контроля доступа должны включать положения о том, какой доступ регистрируется.
Например, если суперпользователь или администратор может редактировать профили других... Это то, что должно быть зафиксировано. Другие
примеры включают обнаруженные нарушения или попытки нарушения механизмов контроля доступа.

=== Использование косвенных ссылок
Не многие приложения используют это, но вы можете использовать *косвенные* ссылки. В этом случае вы можете запустить свои ссылки через хеширование,
кодирование или другую функцию на сервере, так что идентификатор, который видит клиент, не будет фактической ссылкой,
которую обрабатывает сервер. Это несколько снизит эффективность (обычный компромисс для безопасности) и по-прежнему может быть угадано, перебором или обратной разработкой.

Этот подход не должен быть единственной используемой защитой. Его можно использовать как дополнительный уровень. Ваш сервер должен
реализовать логику сопоставления клиентских (косвенных) и серверных (прямых) ссылок.

=== Контроль доступа и API
Часто API или конечные точки RESTFul полагаются на неизвестность, статический «ключ» или отсутствие воображения со стороны пользователя для управления доступом.
Хорошие варианты, такие как цифровые подписанные JSON Web Tokens (https://jwt.io), являются хорошим вариантом для аутентификации API и контроля доступа с использованием
комбинации утверждений и цифровой/криптографической подписи для проверки потребителя. Другие появляющиеся стандарты, такие как
Secure Token Binding, обещают «криптографическое состояние» для веб-сервисов в заголовках запросов...
https://tools.ietf.org/html/draft-ietf-tokbind-protocol-10

https://tools.ietf.org/html/draft-ietf-tokbind-negotiation-05

https://tools.ietf.org/html/draft-ietf-tokbind-https-06
