== Прямые ссылки на объекты

Прямые ссылки на объекты — это когда приложение использует предоставленные клиентом входные данные для доступа к данным и объектам.

=== Примеры

Примеры прямых ссылок на объекты с использованием метода GET могут выглядеть примерно так:

`https://some.company.tld/dor?id=12345`

`https://some.company.tld/images?img=12345`

`https://some.company.tld/dor/12345`

=== Другие методы

POST, PUT, DELETE или другие методы также потенциально уязвимы и в основном отличаются только методом и потенциальной полезной нагрузкой.

== *Небезопасные* прямые ссылки на объекты

Они считаются небезопасными, когда ссылка не обрабатывается должным образом и позволяет обходить авторизацию или раскрывать личные данные, которые могут быть использованы для выполнения операций или доступа к данным, которые пользователь не должен иметь возможности выполнять или получать доступ.
Допустим, вы как пользователь заходите на просмотр своего профиля, и URL выглядит примерно так:

`https://some.company.tld/app/user/23398`

\... и вы можете просмотреть свой профиль там. Что произойдет, если вы перейдете к:

`https://some.company.tld/app/user/23399` ... или используйте другой номер в конце. Если вы можете манипулировать номером (идентификатором пользователя) и просматривать профиль другого человека, то ссылка на объект небезопасна. Это, конечно, можно проверить или расширить за пределы методов GET для просмотра данных, но также и для манипулирования данными.

=== Еще полезное чтение
Прежде чем мы перейдем к практике, вот несколько полезных материалов по теме «Небезопасные прямые ссылки на объекты»:

* link:++https://www.owasp.org/index.php/Testing_for_Insecure_Direct_Object_References_(OTG-AUTHZ-004)++[]
* https://www.owasp.org/index.php/Top_10-2017_A5-Broken_Access_Control
* https://cheatsheetseries.owasp.org/cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.html
* https://www.owasp.org/index.php/Top_10_2013-A4-Insecure_Direct_Object_References
* http://cwe.mitre.org/data/definitions/639.html
