==== Что такое HTTP-прокси

Прокси — это некое приложение-переадресатор, которое подключает вашего HTTP-клиента к внутренним ресурсам.
HTTP-клиентами могут быть браузеры или приложения, такие как curl, SOAP UI, Postman и т. д.
Обычно эти прокси используются для маршрутизации и получения доступа в Интернет, когда нет прямого подключения к Интернету от самого клиента.
Поэтому HTTP-прокси также идеально подходят для тестирования вашего приложения.
Вы всегда можете использовать записи журнала прокси, чтобы увидеть, что на самом деле было отправлено от клиента на сервер.
Таким образом, вы можете проверить заголовки запросов и ответов, а также XML, JSON или другие полезные данные.

HTTP-прокси получают запросы от клиента и ретранслируют их.
Они также обычно записывают их.
Они действуют как посредник.
Они даже отлично работают с HTTPS или без него, если ваш клиент или браузер доверяют сертификату HTTP-прокси.

{nbsp} +

==== Возможности прокси-сервера ZAP

С помощью ZAP вы можете записывать трафик, проверять трафик, изменять запросы и ответы от браузера и к нему, а также получать отчеты о ряде известных уязвимостей, которые ZAP обнаруживает посредством проверки трафика.
Пассивная и активная отчетность по проблемам безопасности обычно используется в конвейерах непрерывной доставки, которые используют ZAP без графического интерфейса пользователя.
Здесь мы будем использовать ZAP интерактивно и в основном для просмотра и изменения запросов с целью поиска уязвимостей и решения задач.
ZAP имеет графический пользовательский интерфейс, но теперь также имеет HUD Heads-On-Display, который использует соединение веб-сокета между браузером и прокси-сервером ZAP.

{nbsp} +

==== Следующие страницы

Вы можете просмотреть все страницы уроков или щелкнуть по этим ссылкам, чтобы пропустить некоторые страницы.

* link:start.mvc#lesson/HttpProxies.lesson/1[Настройка] OWASP ZAP и браузера
* link:start.mvc#lesson/HttpProxies.lesson/5[Фильтрация] запросов с помощью ZAP
* link:start.mvc#lesson/HttpProxies.lesson/6[Назначение прокси] с помощью ZAP
* link:start.mvc#lesson/HttpProxies.lesson/7[Повторное воспроизведение запросов] с помощью ZAP
* link:start.mvc#lesson/HttpProxies.lesson/8[Повторное воспроизведение запросов] с помощью Burp
