== Конфиденциальность

Конфиденциальность — это «свойство, согласно которому информация не предоставляется и не раскрывается неавторизованным лицам, организациям или процессам».
Другими словами, конфиденциальность требует, чтобы неавторизованные пользователи не имели доступа к конфиденциальным ресурсам.
Конфиденциальность должна быть сбалансирована с доступностью; авторизованные лица должны по-прежнему получать доступ к ресурсам, на которые им были предоставлены разрешения.

Хотя конфиденциальность похожа на «приватность», эти два слова не являются взаимозаменяемыми.
Вместо этого конфиденциальность является компонентом конфиденциальности; конфиденциальность реализуется для защиты ресурсов от неавторизованных лиц.

{nbsp} +

=== Примеры, которые ставят под угрозу конфиденциальность:

** хакер получает доступ к базе данных паролей компании
** конфиденциальное электронное письмо отправляется не тому лицу
** хакер читает конфиденциальную информацию, перехватывая и прослушивая передачу информации

{nbsp} +

=== Примеры методов, обеспечивающих конфиденциальность

** шифрование данных
** правильно реализованная аутентификация и контроль доступа
*** надежно сохраненные пароли
*** многофакторная аутентификация (MFA)
*** биометрическая верификация
** минимизация количества мест/раз появления информации
** физические меры безопасности, такие как должным образом защищенные серверные комнаты
