== Хранение токенов JWT

При получении токена JWT вам необходимо сохранить его на стороне клиента. Существует два основных варианта:

- Сохранить токен в cookie
- Сохранить токен в локальном/сеансовом хранилище

=== Файлы cookie

Файлы cookie — это самая простая форма, все браузеры поддерживают файлы cookie в течение длительного времени. Лучше всего пометить файл cookie как `HttpOnly`, чтобы гарантировать, что скрипты не смогут прочитать файл cookie, и как `Secure`, чтобы файл cookie
отправлялся только по HTTPS.

Примечание: использование файла cookie не означает, что вы должны поддерживать состояние, хранящееся на сервере, как это было раньше с использованием старых сеансовых файлов cookie. Токен JWT является автономным и может/должен содержать всю информацию, необходимую для полного отсутствия состояния, файл cookie используется только в качестве транспортного механизма.

=== Веб-хранилище

В этом случае вы сохраняете токен на стороне клиента в веб-хранилище HTML5.

=== Выбор, риски безопасности

Веб-хранилище доступно через JavaScript, работающий на том же домене, поэтому скрипт будет иметь доступ к
веб-хранилищу. Поэтому, если сайт уязвим для атаки с использованием межсайтового скриптинга, скрипт сможет прочитать токен
из веб-хранилища. Подробнее о том, как работает эта атака, см. в уроке XSS.

С другой стороны, использование файлов cookie имеет другую проблему, а именно, они уязвимы для атаки с использованием подделки межсайтовых запросов. В этом случае злоумышленник пытается вызвать действие на веб-сайте, для которого у вас есть токен. Подробнее о том, как работает эта атака, см. в уроке CSRF.

Лучшей рекомендацией является выбор подхода на основе файлов cookie. На практике легче защититься от
атаки CSRF. С другой стороны, многие фреймворки JavaScript защищают пользователя от атаки XSS, применяя правильное
кодирование, эта защита идет «из коробки». Защита от CSRF иногда не предоставляется по умолчанию и требует работы.
В конце концов, посмотрите, что предлагает вам фреймворк, но в большинстве случаев XSS-атака дает злоумышленнику больше возможностей.
