== Неправильное использование заявления

Далее мы рассмотрим последствия для безопасности неправильного использования заявления Key ID (`kid`) в JSON Web Tokens (JWT).

=== JSON Key ID (kid)

Идентификатор ключа (kid) указывает, какой ключ из набора JSON Web Key Set (JWKS) следует использовать для проверки подписи JWT.
При неправильном использовании злоумышленники могут воспользоваться этой уязвимостью, чтобы получить несанкционированный доступ к конфиденциальным ресурсам или выполнить повышение привилегий.

Пример KID будет выглядеть следующим образом:

[source]
----
{
  "alg": "RS256",
  "kid": "my_rsa_key"
}
----

=== Уязвимость

Когда утверждение `kid` используется не по назначению, это обычно означает, что значение "kid" подделывается, чтобы указывать на другой ключ, а не тот, который использовался для подписи токена.
Такая подделка может привести к различным проблемам безопасности:

* **Атака с путаницей ключей**: в этой атаке злоумышленник подделывает значение утверждения "kid", чтобы указывать на другой ключ, а не тот, который использовался для подписи токена.
В результате получатель JWT проверит подпись, используя неправильный ключ, что позволит злоумышленнику выдавать себя за других пользователей или выполнять несанкционированные действия.

* **Перечисление ключей**: если утверждение `kid` не защищено должным образом или представляет собой просто увеличивающееся число или легко предсказуемое значение, злоумышленник может попытаться угадать или перечислить допустимые значения `kid`.
Поступая так, они могут потенциально подделывать JWT с другими значениями `kid`, чтобы найти уязвимости или слабые места в системе.

* **Подмена ключа**: в этой атаке злоумышленник создает JWT с поддельным утверждением `kid`, указывающим на несуществующий или недействительный ключ.

* **Перезапись ключа**: злоумышленник может попытаться перезаписать или изменить утверждение `kid` во время передачи или обработки токена, чтобы указать на другой ключ, нежели изначально предполагалось.

* **Токены без подтверждения**: если система не требует наличия утверждения `kid`, злоумышленник может попытаться создать JWT, вообще не включая утверждение `kid`.
Это упущение может привести к уязвимостям, если получатель предполагает ключ по умолчанию или известный ключ, что может быть небезопасно.

* **Небезопасное хранилище ключей**: Если утверждение «kid» сочетается с другими слабыми методами безопасности, такими как хранение ключей в открытом виде или использование слабого шифрования, злоумышленник может получить допустимые значения «kid» и использовать связанные ключи.

==== Шаги эксплуатации:

- Определите конечную точку kid: злоумышленник должен сначала найти конечную точку kid в логике обработки JWT приложения или любых открытых конфигурациях.

- Сгенерируйте вредоносный JWT: создайте JWT с вредоносными утверждениями, изменив или добавив утверждения для получения несанкционированного доступа или повышения привилегий.

- Сгенерируйте `kid`, который позволит вам узнать ключ проверки.

- Отправьте JWT на сервер: отправьте созданный JWT с вредоносными утверждениями на сервер.

- Проверка сервера: получив JWT, сервер проверяет подпись, используя «созданное» KID.

- Успешная атака: если сервер использует слабый или измененный ключ для проверки JWT, злоумышленник получает несанкционированный доступ или выполняет свой предполагаемый эксплойт.

=== Смягчение

Чтобы предотвратить неправомерное использование утверждения JWT с KID, разработчикам и специалистам по безопасности следует следовать этим рекомендациям:

- Проверка: всегда проверяйте утверждение «kid» и убедитесь, что оно указывает на доверенный ключ, подходящий для проверки подписи.

- Ротация ключей: регулярно меняйте ключи, используемые для подписи JWT, и соответствующим образом обновляйте соответствующие утверждения «kid».

- Использование надежных ключей: убедитесь, что для подписи токенов используются надежные криптографические ключи.

- Контроль доступа: ограничьте доступ к ключам и службам подписи только авторизованным сотрудникам.

- Ограничение скорости: внедрите ограничение скорости, чтобы злоумышленники не могли перебирать возможные значения «kid».

- Мониторинг: отслеживайте и регистрируйте действия, связанные с JWT, для обнаружения потенциального неправомерного использования или подозрительного поведения.

Следуя этим рекомендациям, вы можете снизить риск неправомерного использования JWT-заявлений с полем «kid» и повысить общую безопасность вашей системы.
