== Неправильное использование претензий

Неправильное использование претензий заголовков может произойти, если информация заголовка была подделана или обработана ненадлежащим образом

=== URL-адрес веб-ключа JSON (JKU)

JKU является частью спецификации JWT, которая позволяет потребителю JWT получить открытый ключ, необходимый для динамической проверки подписи токена.
Это URL-адрес, который указывает на конечную точку набора веб-ключей JSON (JWKS), которая содержит открытые ключи, используемые эмитентом для подписи JWT.

Пример JKU будет выглядеть следующим образом:

[source]
----
{
"jku": "https://example.com/.well-known/jwks.json"
}
----

=== Уязвимость: неправомерное использование JWT-заявлений с JKU

Уязвимость возникает, когда JWT подписан слабым или предсказуемым ключом, а сервер предоставляет JKU, который указывает на внешнее расположение, где размещен открытый ключ.

Злоумышленники могут использовать эту уязвимость, создав JWT с вредоносными заявлениями и используя `jku`, чтобы обмануть сервер и заставить его проверить JWT с помощью слабого или измененного ключа.
Все зависит от библиотеки, используемой внутри приложения.
Некоторые библиотеки по умолчанию блокируют загрузку со случайного сервера и используют список разрешенных URL-адресов.
Однако фильтрация по URL-адресам довольно сложна в реализации, и ее также можно обойти.

==== Шаги эксплуатации:

- **Определите конечную точку JKU**: злоумышленнику сначала необходимо найти конечную точку JKU в логике обработки JWT приложения или в любых открытых конфигурациях.

- **Создание вредоносного JWT**: создание JWT с вредоносными утверждениями, изменение или добавление утверждений для получения несанкционированного доступа или повышения привилегий.

- **Подписание JWT**: использование собственного закрытого ключа для подписания вредоносного JWT.

- **Отправка JWT на сервер**: отправка созданного JWT с вредоносными утверждениями на сервер.

- **Проверка сервера**: сервер, получив JWT, проверяет подпись с помощью открытого ключа, полученного из конечной точки JWKS.

- **Успешная атака**: если сервер использует слабый или измененный ключ для проверки JWT, злоумышленник получает несанкционированный доступ или выполняет предполагаемый эксплойт.

=== Смягчение

Чтобы предотвратить неправомерное использование JWT-заявлений с JKU, разработчикам и специалистам по безопасности следует следовать этим рекомендациям:

- **Белый список**: используйте белый список, чтобы проверить, присутствует ли полученный JKU из токена в разрешенном списке.
Будьте осторожны при сравнении URL-адресов с помощью функций сравнения строк, вместо этого используйте белый список и проверяйте весь URL-адрес из `jku`.

- **Статические ключи**: избегайте использования JKU с открытыми ключами, размещенными на внешних конечных точках.
Вместо этого используйте статические ключи, которые надежно управляются и регулярно обновляются.

- **Проверка подписи**: убедитесь, что сервер правильно проверяет подпись JWT и отклоняет токены с недействительными или измененными подписями.

- **Проверка JWT**: тщательно проверяйте и дезинфицируйте все JWT-заявления, чтобы предотвратить атаки с инъекцией и несанкционированный доступ.

- **Аудит и мониторинг**: Регулярно проводите аудит использования JWT, отслеживайте подозрительную активность и внедряйте механизмы обнаружения аномалий.

- **Тестирование безопасности**: Регулярно проводите тестирование безопасности, включая тестирование на проникновение и обзоры кода, чтобы выявлять и устранять потенциальные уязвимости.
