== Компрометация конфиденциальности с помощью инъекции SQL-кода
Если система уязвима для инъекций SQL-кода, аспекты триады CIA этой системы могут быть легко скомпрометированы _(если вы не знакомы с триадой CIA, ознакомьтесь с уроком по триаде CIA в общей категории)_.

В следующих трех уроках вы узнаете, как скомпрометировать каждый аспект триады CIA, используя такие методы, как _инъекции строк SQL_ или _цепочка запросов_.

В этом уроке мы рассмотрим *конфиденциальность*.
Конфиденциальность может быть легко скомпрометирована злоумышленником с помощью инъекции SQL; например, успешная инъекция SQL может позволить злоумышленнику прочитать конфиденциальные данные, такие как номера кредитных карт, из базы данных.

=== Что такое инъекция SQL-кода?
Если приложение создает запросы SQL, просто объединяя предоставленные пользователем строки с запросом, приложение, скорее всего, очень восприимчиво к инъекции SQL-кода. +
Более конкретно, если предоставленная пользователем строка просто объединяется с SQL-запросом без какой-либо очистки или подготовки, то вы можете изменить поведение запроса, просто вставив кавычки в поле ввода.

Например, вы можете закончить строковый параметр кавычками и ввести свой собственный SQL после этого.

=== Теперь ваша очередь!

Вы — сотрудник по имени John *Smith*, работающий в крупной компании.

В компании есть внутренняя система, которая позволяет всем сотрудникам видеть свои собственные внутренние данные, такие как отдел, в котором они работают, и их зарплату.

Система требует, чтобы сотрудники использовали уникальный _TAN аутентификации_ для просмотра своих данных. +
Ваш текущий TAN — *3SL99A*.

Поскольку вы всегда стремитесь быть самым высокооплачиваемым сотрудником, вы хотите использовать систему так, чтобы вместо просмотра собственных внутренних данных _вы хотели посмотреть данные всех своих коллег_, чтобы проверить их текущие зарплаты.

Используйте форму ниже и попробуйте получить все данные о сотрудниках из таблицы *employees*. Вам не нужно знать конкретные имена или TAN, чтобы получить нужную информацию. +
Вы уже выяснили, что запрос, выполняющий ваш запрос, выглядит следующим образом:
------------------------------------------------------------
"SELECT * FROM employees WHERE last_name = '" + name + "' AND auth_tan = '" + auth_tan + "'";
------------------------------------------------------------
