=== Язык определения данных (DDL)

Язык определения данных включает команды для определения структур данных. Команды DDL обычно используются для определения схемы базы данных. Схема относится к общей структуре или организации базы данных и. в базах данных SQL включает такие объекты, как таблицы, индексы, представления, отношения, триггеры и многое другое.

Если злоумышленник успешно «внедряет» команды SQL типа DDL в базу данных, он может нарушить целостность (используя операторы ALTER и DROP) и доступность (используя операторы DROP) системы.

* Команды DDL используются для создания, изменения и удаления структуры объектов базы данных.
* CREATE - создание объектов базы данных, таких как таблицы и представления
* ALTER - изменение структуры существующей базы данных
* DROP - удаление объектов из базы данных
* Example:
** CREATE TABLE employees( +
   &nbsp;&nbsp;&nbsp;&nbsp;userid varchar(6) not null primary key, +
   &nbsp;&nbsp;&nbsp;&nbsp;first_name varchar(20), +
   &nbsp;&nbsp;&nbsp;&nbsp;last_name varchar(20), +
   &nbsp;&nbsp;&nbsp;&nbsp;department varchar(20), +
   &nbsp;&nbsp;&nbsp;&nbsp;salary varchar(10), +
   &nbsp;&nbsp;&nbsp;&nbsp;auth_tan varchar(6) +
);
** Этот оператор создает пример таблицы сотрудников, приведенный на странице 2.

Теперь попробуйте изменить схему, добавив столбец «phone» (varchar(20)) в таблицу «employees».
