== Попробуйте! Написание безопасного кода

Теперь пришло время написать свой собственный код!
Ваша задача — использовать JDBC для подключения к базе данных и запроса данных из нее.

*Требования:*

* подключение к базе данных
* выполнение запроса к базе данных, которая защищена от атак SQL-инъекций
* ваш запрос должен содержать как минимум один строковый параметр

*Несколько советов перед началом:* +
Для подключения к базе данных вы можете просто предположить константы *DBURL*, *DBUSER* и *DBPW* как заданные. +
Содержимое вашего запроса не имеет значения, пока SQL является допустимым и соответствует требованиям. +
Весь написанный вами код вставляется в основной метод класса Java с именем "TestClass", который уже импортирует *java.sql.** для вас.

Недостаточно креативен, чтобы придумать свой собственный запрос? Как насчет того, чтобы попытаться извлечь данные пользователя с определенным именем из вымышленной таблицы базы данных под названием *users*.

Например; следующий код скомпилируется без ошибок (но, конечно, не соответствует требованиям для завершения этого урока).

[source,java]
-------------------------------------------------------
try {
    Connection conn = null;
    System.out.println(conn);   //should output 'null'
} catch (Exception e) {
    System.out.println("Oops. Something went wrong!");
}
-------------------------------------------------------

Используйте свои знания и напишите какой-нибудь допустимый код с нуля в окне редактора ниже!
(если вы не можете печатать там, может помочь один раз настроить размер окна браузера, тогда это должно сработать):
