== Специальные символы

[source]
----
/* */ 	 are inline comments
-- , # 	 are line comments

Example: SELECT * FROM users WHERE name = 'admin' -- AND pass = 'pass'
----


[source]
----
;        позволяет объединять запросы в цепочку

Example: SELECT * FROM users; DROP TABLE users;
----

[source]
----
',+,||   позволяет конкатенацию строк
Char()   строки без кавычек

Example: SELECT * FROM users WHERE name = '+char(27) OR 1=1
----

== Специальные операторы

=== Объединение

Оператор Объединение используется для объединения результатов двух или более операторов SELECT.

Правила, которые следует помнить при работе с UNION:

- Количество выбранных столбцов в каждом операторе должно быть одинаковым.
- Тип данных первого столбца в первом операторе SELECT должен совпадать с типом данных
первого столбца во втором (третьем, четвертом, ...) операторе SELECT. То же самое относится ко всем остальным столбцам.

[source]
------
SELECT first_name FROM user_system_data UNION SELECT login_count FROM user_data;
------

Синтаксис UNION ALL также допускает дублирующиеся значения.

=== Объединения

Оператор объединения используется для объединения строк из двух или более таблиц на основе связанного столбца

[source]
-----
SELECT * FROM user_data INNER JOIN user_data_tan ON user_data.userid=user_data_tan.userid;
-----

Более подробную информацию о JOINS можно найти на сайте: https://www.w3schools.com/sql/sql_join.asp
