== Нарушение целостности с помощью цепочки запросов
После нарушения конфиденциальности данных на предыдущем уроке, на этот раз мы нарушим *целостность*
данных с помощью *цепочки запросов* SQL.

Если существует достаточно серьезная уязвимость, инъекция SQL может быть использована для нарушения целостности любых данных в базе данных. Успешная инъекция SQL может позволить злоумышленнику изменить информацию, к которой он даже не должен иметь
доступа.

=== Что такое цепочка запросов SQL?
Цепочка запросов — это именно то, на что она похожа. С помощью цепочки запросов вы пытаетесь добавить один или несколько запросов в конец фактического запроса. Вы можете сделать это с помощью метасимвола *;*. *;* отмечает конец оператора SQL; он позволяет начать другой запрос сразу после исходного запроса без необходимости даже начинать новую строку.

=== Теперь ваша очередь!
Вы только что узнали, что Тоби и Боб, похоже, зарабатывают больше денег, чем вы!
Конечно, вы не можете оставить все как есть. +
Лучше пойдите и _измените свою зарплату, чтобы зарабатывать больше!_

Помните: вас зовут John *Smith*, а ваш текущий TAN — *3SL99A*.
