== Что такое SQL-инъекция?

SQL-инъекция (также называемая SQLi) — один из наиболее распространенных методов веб-хакинга. *Атака SQL-инъекцией заключается во вставке или «внедрении» вредоносного кода через входные данные SQL-запроса от клиента к приложению.* Если с ней не справиться правильно, SQL-инъекция может серьезно повлиять на целостность и безопасность данных.

SQL-инъекции могут происходить, когда неотфильтрованные данные от клиента, такие как ввод из поля поиска, попадают в интерпретатор SQL самого приложения. Если приложение не может правильно очистить пользовательский ввод (используя подготовленные операторы или что-то подобное) или отфильтровать ввод от специальных символов, хакеры могут манипулировать базовым SQL-оператором в своих интересах. +
Например, если ввод не отфильтрован для метасимволов SQL, таких как *--* (который комментирует остальную часть строки) или *;* (который завершает SQL-запрос), может произойти SQL-инъекция.

{nbsp} +

== Пример SQL-инъекции

Например, рассмотрим веб-приложение, которое позволяет пользователям извлекать информацию о пользователе, просто вводя имя пользователя в поле формы. Вводимые пользователем данные отправляются на сервер и вставляются в SQL-запрос, который затем обрабатывается SQL-интерпретатором.

SQL-запрос для извлечения информации о пользователе из базы данных выглядит следующим образом: +

-------------------------------------------------------
"SELECT * FROM users WHERE name = '" + userName + "'";
-------------------------------------------------------

Переменная *userName* содержит входные данные от клиента и «вводит» их в запрос. +
Если бы входные данные были Smith, запрос стал бы +
-------------------------------------------------------
"SELECT * FROM users WHERE name = 'Smith'";
-------------------------------------------------------
и извлечет все данные для пользователя с именем Smith.

{nbsp} +
Если злоумышленник вводит данные, содержащие символы или строки, имеющие «специальное» значение для интерпретатора SQL (например, *;*, *--* или *'*), и данные не были правильно очищены или проверены, злоумышленник может изменить предполагаемое поведение SQL-запроса, чтобы выполнить другие (вредоносные) действия в базе данных.

Вот поле ввода. Попробуйте ввести здесь немного SQL, чтобы лучше понять, как изменяется запрос.
