== Слепая инъекция SQL

Слепая инъекция SQL — это тип атаки с использованием инъекции SQL, которая задает базе данных вопросы «истина» или «ложь» и определяет ответ на основе ответа приложения. Эта атака часто используется, когда веб-приложение настроено на отображение общих сообщений об ошибках, но не смягчило код, уязвимый для инъекции SQL.

=== Разница

Давайте сначала начнем с разницы между обычной инъекцией SQL и слепой инъекцией SQL. При обычной инъекции SQL отображаются сообщения об ошибках из базы данных, и предоставляется достаточно информации, чтобы выяснить,
как работает запрос. Или в случае инъекции SQL на основе UNION приложение не отображает информацию
непосредственно на веб-странице. Поэтому в случае, когда ничего не отображается, вам нужно будет начать задавать базе данных вопросы на основе истинного или ложного утверждения. Вот почему слепую инъекцию SQL гораздо сложнее эксплуатировать.

Существует несколько различных типов слепых инъекций SQL: инъекции SQL на основе содержимого и времени.

=== Пример

В этом случае мы пытаемся задать базе данных логический вопрос на основе уникального идентификатора, например
предположим, у нас есть следующий URL: `https://my-shop.com?article=4`
На стороне сервера этот запрос будет преобразован следующим образом:

----
SELECT * FROM articles WHERE article_id = 4
----

Когда мы хотим это использовать, мы меняем URL на: `https://shop.example.com?article=4 AND 1=1`
Это будет переведено на:

----
SELECT * FROM articles WHERE article_id = 4 and 1 = 1
----

Если браузер вернет ту же страницу, что и раньше при использовании `https://shop.example.com?article=4`, вы знаете,
что веб-сайт уязвим для слепой инъекции SQL.
Если браузер отвечает, что страница не найдена или что-то еще, вы знаете, что слепая инъекция SQL может не сработать.
Теперь вы можете изменить запрос SQL и протестировать, например: `https://shop.example.com?article=4 AND 1=2`, который ничего не вернет, потому что запрос возвращает false.

Как мы на самом деле можем этим воспользоваться? Выше мы только задали базе данных тривиальный вопрос, но вы можете,
например, также использовать следующий URL: `https://shop.example.com?article=4 AND substring(database_version(),1,1) = 2`

В большинстве случаев вы начинаете с поиска типа используемой базы данных, на основе типа базы данных вы можете найти
системные таблицы базы данных, вы можете перечислить все таблицы, присутствующие в базе данных. С этой информацией
вы можете начать получать информацию из всех таблиц и можете сделать дамп базы данных.
Имейте в виду, что этот подход может не работать, если привилегии базы данных настроены правильно (то есть системные таблицы не могут быть запрошены пользователем, используемым для подключения из веб-приложения к базе данных).

Другой способ называется SQL-инъекцией на основе времени, в этом случае вы попросите базу данных подождать, прежде чем вернуть
результат. Вам может понадобиться использовать это, если вы полностью слепы. Это означает, что нет никакой разницы между данными ответа.
Чтобы добиться такого вида SQL-инъекции, вы можете использовать:

----
article = 4; sleep(10) --
----
