== Что такое SQL?

SQL — это стандартизированный (ANSI в 1986 г., ISO в 1987 г.) язык программирования, который используется для управления реляционными базами данных и выполнения различных операций с данными в них.

База данных — это набор данных. Данные организованы в строки, столбцы и таблицы и индексированы для более эффективного поиска релевантной информации.

Пример таблицы SQL, содержащей данные о сотрудниках; имя таблицы — «сотрудники»:

Таблица «Сотрудники»
|===
|userid |first_name |last_name |department |salary |auth_tan |

|32147|Paulina|Travers|Accounting|$46.000|P45JSI|
|89762|Tobi|Barnett|Development|$77.000|TA9LL1|
|96134|Bob|Franco|Marketing|$83.700|LO9S2V|
|34477|Abraham|Holman|Development|$50.000|UU2ALK|
|37648|John|Smith|Marketing|$64.350|3SL99A|

|===

Компания сохраняет в своих базах данных следующую информацию о сотрудниках:
уникальный номер сотрудника («userid»), фамилия, имя, отдел, зарплата и номер аутентификации транзакции («auth_tan»). Каждый из этих фрагментов информации хранится в отдельном столбце, а каждая строка представляет одного сотрудника компании.

Запросы SQL можно использовать для изменения таблицы базы данных и ее индексных структур, а также для добавления, обновления и удаления строк данных.

Существует три основные категории команд SQL:

* Язык манипулирования данными (DML)
* Язык определения данных (DDL)
* Язык управления данными (DCL)

Каждый из этих типов команд может использоваться злоумышленниками для нарушения конфиденциальности, целостности и/или доступности системы. Продолжайте изучать урок, чтобы узнать больше о типах команд SQL и их связи с целями защиты.

Если вы все еще испытываете трудности с SQL и вам нужна дополнительная информация или практика, вы можете посетить http://www.sqlcourse.com/ для бесплатного и интерактивного онлайн-обучения.

=== Теперь ваша очередь!
Посмотрите на пример таблицы.
Попробуйте получить отдел сотрудника Боба Франко.
Обратите внимание, что вам предоставлены полные права администратора в этом назначении, и вы можете получить доступ ко всем данным без аутентификации.
