== Вопросы безопасности

Это было и остается проблемой для многих веб-сайтов, когда вы теряете свой пароль, веб-сайт запрашивает у вас
секретный вопрос, на который вы ответили во время процесса регистрации. В большинстве случаев этот список содержит фиксированное
количество вопросов, которые иногда даже имеют ограниченный набор ответов. Чтобы использовать эту функцию,
пользователь должен иметь возможность выбрать вопрос отдельно и также ввести ответ. Таким образом, пользователи не будут делиться
вопросом, что усложняет задачу злоумышленнику.

Одна важная вещь, которую следует помнить, — ответы на эти вопросы безопасности должны обрабатываться с тем же уровнем безопасности, который применяется для хранения пароля в базе данных. В случае утечки базы данных злоумышленник не должен иметь
возможности выполнить сброс пароля на основе ответа на вопрос безопасности.

В наши дни пользователи делятся в социальных сетях таким количеством информации, что становится сложно использовать контрольные вопросы для сброса пароля, хороший ресурс для контрольных вопросов: http://goodsecurityquestions.com/

== Задание

Пользователи могут восстановить свой пароль, если они смогут правильно ответить на секретный вопрос. На этой странице «Забыли пароль» нет механизма блокировки. Ваше имя пользователя — «webgoat», а ваш любимый цвет — «red». Цель — восстановить пароль другого пользователя. Вы можете попробовать: «tom», «admin» и «larry».
