== Как предотвратить злоупотребление функцией сброса пароля

Узнав, как злоупотреблять функцией сброса пароля, вы теперь также должны знать, как защитить свой собственный веб-сайт от таких атак. Если вы хотите получить подробное описание всех методов смягчения, посмотрите здесь: https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html

В этом уроке будут обобщены важные моменты, упомянутые в шпаргалке выше.

=== Как использовать контрольные вопросы для проверки пользователя
Контрольные вопросы — это простой способ узнать информацию о действительности пользователя, не запрашивая у него данные для проверки. Проблема в том, что существует не так много типов контрольных вопросов, и ответы на большинство вопросов одинаковы у многих пользователей. Это позволяет злоумышленнику просто угадать вопрос и ответ.

Простой способ усложнить угадывание контрольного вопроса — позволить пользователю самому решить, на какой вопрос он хочет ответить. Дополнительную информацию по этой теме можно найти здесь: https://cheatsheetseries.owasp.org/cheatsheets/Choosing_and_Using_Security_Questions_Cheat_Sheet.html#user-defined-security-questions

=== Отправка данных по сети
Все, что отправляется по сети в любом направлении, может быть прочитано злоумышленником. Некоторые данные облегчают злоумышленнику сбор важной информации об учетной записи пользователя, которая помогает ему обойти ограничения на вход и сброс пароля. Поэтому старайтесь не отправлять по сети информацию об учетной записи (например, имена пользователей, адреса электронной почты и т. д.) во время процедуры сброса пароля, которая не была введена самим пользователем!

Например: если вы отправляете ссылку на сброс пароля пользователю по электронной почте, ни в коем случае не включайте имя пользователя в саму форму сброса пароля! Пользователю не обязательно видеть свое имя пользователя в форме, поскольку незлонамеренный пользователь уже знает его имя. Сделайте сбор дополнительной информации злоумышленником максимально сложным.

=== О токене сброса пароля
Токены сброса пароля позволяют пользователю сбросить пароль без изначально безопасной информации о проверке пользователя. Следовательно, они должны быть безопасными. Такой токен должно быть сложно угадать. Токен также должен быть действителен только в течение короткого периода времени и должен быть недействительным после того, как пользователь успешно сбросит свой пароль.

=== Ведение журнала действий пользователя
Одно только ведение журнала не может предотвратить атаки, но может облегчить определение того, произошла ли атака и как злоумышленник пытался обойти систему безопасности. Вы также можете использовать журналы, чтобы определить, действительно ли была взломана учетная запись и нужно ли ее вернуть законному пользователю. Действия, которые вы можете регистрировать: Как были получены ответы на контрольные вопросы? Когда произошел доступ к ссылке сброса пароля по сравнению с временем отправки электронного письма? Были ли неудачные попытки?

=== Двухфакторная аутентификация
Всегда безопаснее выполнять процесс аутентификации двумя или более отдельными способами на двух или более отдельных устройствах. Если пользователь хочет сбросить свой пароль, вы можете попросить его ввести коды подтверждения, отправленные ему по SMS, Messenger или аналогичному средству. Это затрудняет для злоумышленника обход процесса подтверждения, поскольку ему нужен физический доступ к другому устройству.
С другой стороны, это требует от пользователя предоставления вам дополнительной информации по вопросу связи с ним, что не приветствуется всеми.

=== Дальнейшее чтение
Мы настоятельно рекомендуем вам более подробно ознакомиться с шпаргалкой, ссылка на которую приведена во введении! Функция сброса пароля легко может быть использована злоумышленником, если она реализована неправильно. Вы можете усложнить злоумышленнику ее использование, просто следуя нескольким предложениям, приведенным здесь и в шпаргалке!
