== Создание ссылки для сброса пароля

При создании ссылки для сброса пароля необходимо убедиться, что:

- Это уникальная ссылка со случайным токеном
- Вы можете использовать ее только один раз
- Ссылка действительна только в течение ограниченного периода времени.

Отправка ссылки со случайным токеном означает, что злоумышленник не сможет начать простую DOS-атаку на ваш сайт, начав блокировать пользователей. Ссылку нельзя использовать больше одного раза, что делает невозможным повторное изменение пароля. Тайм-аут необходим для ограничения окна атаки. Наличие ссылки открывает множество возможностей для злоумышленника.

== Задание

Попробуйте сбросить пароль Тома (tom@webgoat-cloud.org) на свой собственный выбор и войдите как Том с этим паролем. Примечание: для этого урока невозможно использовать OWASP ZAP. Кроме того, браузеры могут не работать; инструменты командной строки, такие как `curl` и тому подобное, будут более успешными для этой атаки.

Том быстро реагирует, когда дело касается его пароля. Он всегда сбрасывает настройки сразу после получения письма со ссылкой.
