= Сброс пароля

== Концепция

Этот урок посвящен функциональности сброса пароля, которая чаще всего является упускаемой из виду частью приложения,
что приводит к всевозможным интересным логическим ошибкам.

== Цели

Изучить, как безопасно реализовать функциональность сброса пароля в вашем приложении.

== Введение

Каждый из нас уже использовал функциональность сброса пароля на веб-сайтах. Каждый веб-сайт реализует
эту функциональность по-разному. На некоторых сайтах вам нужно ответить на какой-то вопрос, на других сайтах вам будет отправлено электронное письмо
со ссылкой активации. В этом уроке мы рассмотрим некоторые из наиболее распространенных функций сброса пароля и покажем, где это может пойти не так.

Есть компании, которые отправляют пользователю пароль в виде открытого текста по электронной почте.
Для пары примеров вы можете взглянуть на http://plaintextoffenders.com/. Здесь вы найдете веб-сайты, которые по-прежнему отправляют вам открытый пароль по электронной почте.
Это не только должно заставить вас усомниться в безопасности сайта, но это также означает, что они хранят ваш пароль в открытом виде!
