=== Шаг 4: Добавьте задание в свой урок

С заданием пользователь может практиковаться в рамках урока. Урок может состоять из нескольких заданий, каждое задание
должно реализовывать класс `AssignmentEndpoint`, давайте рассмотрим пример:

[source,java]
----
import org.owasp.webgoat.container.assignments.AssignmentEndpoint;@RestController // <1>
@AssignmentHints({"lesson-template.hints.1", "lesson-template.hints.2", "lesson-template.hints.3"}) // <2>
public class SampleAttack implements AssignmentEndpoint { // <3>

    private final String secretValue = "secr37Value";

    @Autowired
    private UserSessionData userSessionData; // <4>

    @PostMapping("/lesson-template/sample-attack") <5>
    @ResponseBody
    public AttackResult completed(@RequestParam("param1") String param1, @RequestParam("param2") String param2) { <6>
        if (userSessionData.getValue("some-value") != null) {
            // do any session updating you want here ... or not, just comment/example here
            //return builder.failed(this).feedback("lesson-template.sample-attack.failure-2").build();
        }

        //overly simple example for success. See other existing lessons for ways to detect 'success' or 'failure'
        if (secretValue.equals(param1)) {
            return success(this) // <7>
                    .output("Custom Output ...if you want, for success")
                    .feedback("lesson-template.sample-attack.success")
                    .build();
            //lesson-template.sample-attack.success is defined in src/main/resources/i18n/WebGoatLabels.properties
        }

        // else
        return failed(this) // <8>
                .feedback("lesson-template.sample-attack.failure-2")
                .output("Custom output for this failure scenario, usually html that will get rendered directly ... yes, you can self-xss if you want")
                .build();
    }
----
<1> Каждое задание — это просто Spring RestController
<2> Каждое задание может иметь список подсказок. Фактический текст должен быть помещен в `WebGoatLabels.properties` в папке `src/main/resources/{lessonName}/i18n`
<3> Каждое задание должно реализовывать интерфейс `AssignmentEndpoint`. Это интерфейс маркера, поэтому не нужно реализовывать методы
<4> Поскольку задание — это класс на основе Spring, вы можете автоматически связать каждый компонент, управляемый Spring, необходимый для задания
<5> Каждое задание должно иметь как минимум одно сопоставление с сигнатурой метода (см. 6)
<6> Когда пользователь пытается решить задание, вам нужно вернуть `AttackResult`
<7> Возврат результата успешной атаки, когда пользователь решил урок
<8> Возврат неудавшейся атаки, когда пользователь не решил урок

{nbsp} +

Как видите, назначение — это REST-контроллер, который должен иметь как минимум один метод со следующей сигнатурой:

[source]
----
@RequestMapping(method = "...", path = "/lesson-template/solution")
@ResponseBody
public AttackResult solve(String param) {
  ...
}
----

=== Дополнительные конечные точки

В задание можно добавить другие конечные точки для поддержки различных случаев для задания, например:

[source]
----
@GetMapping("lesson-template/shop/{user}")
@ResponseBody
public List<Item> getItemsInBasket(@PathVariable("user") String user) {
  return List.of(new Item("WG-1", "WebGoat promo", 12.0), new Item("WG-2", "WebGoat sticker", 0.00));
}
----

=== Добавление задания на страницу HTML

Мы упоминали, что урок может состоять из нескольких заданий, WebGoat автоматически их подбирает, а пользовательский интерфейс отображает
панель навигации поверх каждого урока. Страница с заданием изначально будет красной и станет
зеленой, когда пользователь решит задание. Чтобы это сработало, нам нужно добавить в файл HTML:

[source]
----
<div class="lesson-page-wrapper">
  <div class="adoc-content" th:replace="~{doc:lesson-template-attack.adoc}"></div>
  <div class="attack-container">
    <div class="assignment-success"><i class="fa fa-2 fa-check hidden" aria-hidden="true"></i></div>
    <form class="attack-form" accept-charset="UNKNOWN"
          method="POST" name="form"
          action="lesson-template/sample-attack">
      <table>
        <tr>
          <td>two random params</td>
          <td>parameter 1:<input name="param1" value="" type="TEXT" /></td>
          <td>parameter 2:<input name="param2" value="" type="TEXT" /></td>
          <td>
            <input name="submit" value="Submit" type="SUBMIT"/>
          </td>
        </tr>
      </table>
    </form>
    <div class="attack-feedback"></div>
    <div class="attack-output"></div>
  </div>
</div>
----

Таким образом, `action` формы должен соответствовать методу, который определяет проверку, решен ли урок или нет
см. `public AttackResult solved()`

Вот и все. Вы успешно создали свой первый урок WebGoat, включая задание!
